import type { Metadata } from "next";
import "@/styles/globals.scss";
import { inter, golos_text } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${inter.variable} ${golos_text.variable}`}>
      <body id="body">
        {children}
      </body>
    </html>
  );
}
