import type { Metadata } from "next";
import "@/styles/globals.scss";
import { Header, Menu } from "@/lib/widgets";
import { inter, golos_text } from "@/fonts";
import Footer from "@/lib/widgets/Footer/ui/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${inter.variable} ${golos_text.variable}`}>
      <body>
        <Header />
        <Menu />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
